DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:0]/GPUPowerMizerMode=1
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:1]/GPUPowerMizerMode=1
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:2]/GPUPowerMizerMode=1
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:3]/GPUPowerMizerMode=1
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:4]/GPUPowerMizerMode=1
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:5]/GPUPowerMizerMode=1
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:6]/GPUPowerMizerMode=1
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:7]/GPUPowerMizerMode=1
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:8]/GPUPowerMizerMode=1
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:9]/GPUPowerMizerMode=1
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:10]/GPUPowerMizerMode=1
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:11]/GPUPowerMizerMode=1
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:12]/GPUPowerMizerMode=1

DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:0]/GPUGraphicsClockOffset[3]=0
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:1]/GPUGraphicsClockOffset[3]=0
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:2]/GPUGraphicsClockOffset[3]=0
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:3]/GPUGraphicsClockOffset[3]=0
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:4]/GPUGraphicsClockOffset[3]=0
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:5]/GPUGraphicsClockOffset[3]=0
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:6]/GPUGraphicsClockOffset[3]=0
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:7]/GPUGraphicsClockOffset[3]=0
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:8]/GPUGraphicsClockOffset[3]=0
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:9]/GPUGraphicsClockOffset[3]=0
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:10]/GPUGraphicsClockOffset[3]=0
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:11]/GPUGraphicsClockOffset[3]=0
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:12]/GPUGraphicsClockOffset[3]=0

DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:0]/GPUMemoryTransferRateOffset[3]=0
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:1]/GPUMemoryTransferRateOffset[3]=0
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:2]/GPUMemoryTransferRateOffset[3]=0
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:3]/GPUMemoryTransferRateOffset[3]=0
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:4]/GPUMemoryTransferRateOffset[3]=0
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:5]/GPUMemoryTransferRateOffset[3]=0
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:6]/GPUMemoryTransferRateOffset[3]=0
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:7]/GPUMemoryTransferRateOffset[3]=0
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:8]/GPUMemoryTransferRateOffset[3]=0
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:9]/GPUMemoryTransferRateOffset[3]=0
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:10]/GPUMemoryTransferRateOffset[3]=0
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:11]/GPUMemoryTransferRateOffset[3]=0
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:12]/GPUMemoryTransferRateOffset[3]=0

#nvidia-smi -i 0 -ac 3505,1506
#nvidia-smi -i 2 -ac 3505,1455

DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a "[gpu:0]/GPUFanControlState=1"
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a "[gpu:1]/GPUFanControlState=1"
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a "[gpu:2]/GPUFanControlState=1"
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a "[gpu:3]/GPUFanControlState=1"
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a "[gpu:4]/GPUFanControlState=1"
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a "[gpu:5]/GPUFanControlState=1"
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a "[gpu:6]/GPUFanControlState=1"
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a "[gpu:7]/GPUFanControlState=1"
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a "[gpu:8]/GPUFanControlState=1"
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a "[gpu:9]/GPUFanControlState=1"
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a "[gpu:10]/GPUFanControlState=1"
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a "[gpu:11]/GPUFanControlState=1"
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a "[gpu:12]/GPUFanControlState=1"
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a "[fan:0]/GPUTargetFanSpeed=100"
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a "[fan:1]/GPUTargetFanSpeed=100"
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a "[fan:2]/GPUTargetFanSpeed=100"
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a "[fan:3]/GPUTargetFanSpeed=100"
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a "[fan:4]/GPUTargetFanSpeed=100"
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a "[fan:5]/GPUTargetFanSpeed=100"
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a "[fan:6]/GPUTargetFanSpeed=100"
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a "[fan:7]/GPUTargetFanSpeed=100"
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a "[fan:8]/GPUTargetFanSpeed=100"
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a "[fan:9]/GPUTargetFanSpeed=100"
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a "[fan:10]/GPUTargetFanSpeed=100"
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a "[fan:11]/GPUTargetFanSpeed=100"
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a "[fan:12]/GPUTargetFanSpeed=100"
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:0]/GPUGraphicsClockOffset[3]=150
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:1]/GPUGraphicsClockOffset[3]=150
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:2]/GPUGraphicsClockOffset[3]=150
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:3]/GPUGraphicsClockOffset[3]=150
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:4]/GPUGraphicsClockOffset[3]=150
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:5]/GPUGraphicsClockOffset[3]=150
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:6]/GPUGraphicsClockOffset[3]=150
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:7]/GPUGraphicsClockOffset[3]=150
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:8]/GPUGraphicsClockOffset[3]=150
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:9]/GPUGraphicsClockOffset[3]=150
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:10]/GPUGraphicsClockOffset[3]=150
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:11]/GPUGraphicsClockOffset[3]=150
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:12]/GPUGraphicsClockOffset[3]=150

DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:0]/GPUMemoryTransferRateOffset[3]=500
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:1]/GPUMemoryTransferRateOffset[3]=500
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:2]/GPUMemoryTransferRateOffset[3]=500
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:3]/GPUMemoryTransferRateOffset[3]=500
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:4]/GPUMemoryTransferRateOffset[3]=500
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:5]/GPUMemoryTransferRateOffset[3]=500
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:6]/GPUMemoryTransferRateOffset[3]=500
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:7]/GPUMemoryTransferRateOffset[3]=500
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:8]/GPUMemoryTransferRateOffset[3]=500
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:9]/GPUMemoryTransferRateOffset[3]=500
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:10]/GPUMemoryTransferRateOffset[3]=500
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:11]/GPUMemoryTransferRateOffset[3]=500
DISPLAY=:1 XAUTHORITY=/var/lib/mdm/:0.Xauth nvidia-settings -a [gpu:12]/GPUMemoryTransferRateOffset[3]=500

sudo nvidia-smi -pl 120
sudo nvidia-smi -pm 1
